// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX68emJuqz8czHijQsUu6VYlJkZm_UQ7g',
    appId: '1:846269826213:web:ac4dafb5df411c863fb94c',
    messagingSenderId: '846269826213',
    projectId: 'user-crud-9ab2a',
    authDomain: 'user-crud-9ab2a.firebaseapp.com',
    storageBucket: 'user-crud-9ab2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARBSWHwm-hHYz8ASoS4e6kasNdbkuogaA',
    appId: '1:846269826213:android:13bef76a84f7eedd3fb94c',
    messagingSenderId: '846269826213',
    projectId: 'user-crud-9ab2a',
    storageBucket: 'user-crud-9ab2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADToAvkfuCeKn0_vbf-hQDR6GltenzFN8',
    appId: '1:846269826213:ios:4c635e934b9ada6c3fb94c',
    messagingSenderId: '846269826213',
    projectId: 'user-crud-9ab2a',
    storageBucket: 'user-crud-9ab2a.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADToAvkfuCeKn0_vbf-hQDR6GltenzFN8',
    appId: '1:846269826213:ios:4c635e934b9ada6c3fb94c',
    messagingSenderId: '846269826213',
    projectId: 'user-crud-9ab2a',
    storageBucket: 'user-crud-9ab2a.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX68emJuqz8czHijQsUu6VYlJkZm_UQ7g',
    appId: '1:846269826213:web:b4379a5b8f7cc8f53fb94c',
    messagingSenderId: '846269826213',
    projectId: 'user-crud-9ab2a',
    authDomain: 'user-crud-9ab2a.firebaseapp.com',
    storageBucket: 'user-crud-9ab2a.appspot.com',
  );
}
